// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqsuaqoqpjxxeeyjmsrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxc3VhcW9xcGp4eGVleWptc3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzgxODEsImV4cCI6MjA2MTY1NDE4MX0.aar-bEzMb0O0DilgNcWodrm2vNDcKA2yinhOjfiSBc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);